-- 10 Felhasználó beszúrása
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user1', 'password123', 'user1@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user2', 'password456', 'user2@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user3', 'password789', 'user3@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user4', 'password101', 'user4@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user5', 'password202', 'user5@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user6', 'password303', 'user6@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user7', 'password404', 'user7@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user8', 'password505', 'user8@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user9', 'password606', 'user9@example.com');

INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user10', 'password707', 'user10@example.com');

COMMIT;



--6 Izomcsoport beszúrása
INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Mell-Bicepsz', 'Mellkas és bicepsz izmainak edzése');

INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Hát-Tricepsz', 'Hát és tricepsz edzése');

INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Váll-Láb', 'Váll és láb izmainak edzése');

INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Teljes Test', 'Egész testet átmozgató edzés');

INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Core-Tréning', 'Has és mélyizmok erõsítése');

INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Lábnap', 'Alsótest izmainak fejlesztése');

COMMIT;



--10 WORKOUT betöltése
INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (1, 1, TO_DATE('2024-12-01', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (2, 2, TO_DATE('2024-12-02', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (3, 3, TO_DATE('2024-12-03', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (4, 4, TO_DATE('2024-12-04', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (5, 5, TO_DATE('2024-12-05', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (6, 6, TO_DATE('2024-12-06', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (1, 2, TO_DATE('2024-12-07', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (2, 3, TO_DATE('2024-12-08', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (3, 4, TO_DATE('2024-12-09', 'YYYY-MM-DD'));

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (4, 5, TO_DATE('2024-12-10', 'YYYY-MM-DD'));

COMMIT;


--10 exercise betöltése
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Fekvenyomás', 'Mellizom erõsítõ alapgyakorlat súlyzóval');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Húzódzkodás', 'Hátizom és bicepsz erõsítõ gyakorlat saját testsúllyal');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Guggolás', 'Lábedzés alapgyakorlata súlyzóval');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Felhúzás', 'Teljes testet igénybe vevõ alapgyakorlat');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Bicepsz hajlítás', 'Kar izomzatának erõsítése kézisúlyzóval');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Tricepsz lenyomás', 'Tricepsz izom erõsítése csigás gépen');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Vállból nyomás', 'Váll izomzatának fejlesztése súlyzóval');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Plank', 'Core izmok fejlesztése saját testsúllyal');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Kitörés', 'Láb és farizom erõsítõ gyakorlat');

INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Mellhez húzás csigán', 'Hátizmok izolált edzése csigás gépen');

COMMIT;


--10 workout_exercise betöltése
INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (1, 1); -- Fekvenyomás az 1. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (1, 2); -- Húzódzkodás az 1. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (2, 3); -- Guggolás a 2. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (2, 4); -- Felhúzás a 2. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (3, 5); -- Bicepsz hajlítás a 3. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (3, 6); -- Tricepsz lenyomás a 3. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (4, 7); -- Vállból nyomás a 4. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (4, 8); -- Plank a 4. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (5, 9); -- Kitörés az 5. edzéshez

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (5, 10); -- Mellhez húzás csigán az 5. edzéshez

COMMIT;



--10 workout_results betöltés
INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (1, 80.5, 10); -- Fekvenyomás

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (2, 85.0, 8); -- Húzódzkodás

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (3, 100.0, 12); -- Guggolás

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (4, 120.0, 6); -- Felhúzás

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (5, 15.0, 15); -- Bicepsz hajlítás

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (6, 25.0, 12); -- Tricepsz lenyomás

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (7, 60.0, 8); -- Vállból nyomás

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (8, 0.0, 90); -- Plank (idõtartam másodpercben)

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (9, 20.0, 20); -- Kitörés

INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (10, 50.0, 10); -- Mellhez húzás csigán

COMMIT;










