-- 10 Felhasználó beszúrása
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user1', 'password123', 'user1@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user2', 'password456', 'user2@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user3', 'password789', 'user3@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user4', 'password101', 'user4@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user5', 'password202', 'user5@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user6', 'password303', 'user6@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user7', 'password404', 'user7@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user8', 'password505', 'user8@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user9', 'password606', 'user9@example.com');
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
VALUES ('user10', 'password707', 'user10@example.com');

COMMIT;



--6 izomcsoport
INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Mell-Bicepsz', 'Mellkas és bicepsz izmainak edzése');
INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Hát-Tricepsz', 'Hát és tricepsz edzése');
INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Váll-Láb', 'Váll és láb izmainak edzése');
INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Teljes Test', 'Egész testet átmozgató edzés');
INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Core-Tréning', 'Has és mélyizmok erõsítése');
INSERT INTO MUSCLE_GROUP (MUSCLE_GROUP_NAME, DESCRIPTION)
VALUES ('Lábnap', 'Alsótest izmainak fejlesztése');

COMMIT;




--10 exercises betöltése
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Fekvenyomás', 'Mellizom erõsítõ alapgyakorlat súlyzóval');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Húzódzkodás', 'Hátizom és bicepsz erõsítõ gyakorlat saját testsúllyal');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Guggolás', 'Lábedzés alapgyakorlata súlyzóval');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Felhúzás', 'Teljes testet igénybe vevõ alapgyakorlat');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Bicepsz hajlítás', 'Kar izomzatának erõsítése kézisúlyzóval');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Tricepsz lenyomás', 'Tricepsz izom erõsítése csigás gépen');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Vállból nyomás', 'Váll izomzatának fejlesztése súlyzóval');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Plank', 'Core izmok fejlesztése saját testsúllyal');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Kitörés', 'Láb és farizom erõsítõ gyakorlat');
INSERT INTO EXERCISES (EXERCISE_NAME, DESCRIPTION)
VALUES ('Mellhez húzás csigán', 'Hátizmok izolált edzése csigás gépen');

COMMIT;

--10 workouts betöltése
INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user1'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Mell-Bicepsz'),
  DATE '2024-12-01'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user2'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Hát-Tricepsz'),
  DATE '2024-12-02'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user3'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Váll-Láb'),
  DATE '2024-12-03'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user4'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Teljes Test'),
  DATE '2024-12-04'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user5'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Core-Tréning'),
  DATE '2024-12-05'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user6'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Lábnap'),
  DATE '2024-12-06'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user1'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Hát-Tricepsz'),
  DATE '2024-12-07'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user2'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Váll-Láb'),
  DATE '2024-12-08'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user3'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Teljes Test'),
  DATE '2024-12-09'
);

INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (
  (SELECT USER_ID FROM USERS WHERE USERNAME = 'user4'),
  (SELECT MUSCLE_GROUP_ID FROM MUSCLE_GROUP WHERE MUSCLE_GROUP_NAME = 'Core-Tréning'),
  DATE '2024-12-10'
);

COMMIT;





--workout_exercise betöltése
INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (
  (SELECT WORKOUT_ID FROM WORKOUTS W 
     JOIN USERS U ON W.USER_ID = U.USER_ID
     JOIN MUSCLE_GROUP M ON W.MUSCLE_GROUP_ID = M.MUSCLE_GROUP_ID
   WHERE U.USERNAME = 'user1'
     AND M.MUSCLE_GROUP_NAME = 'Mell-Bicepsz'
     AND W.WORKOUT_DATE = DATE '2024-12-01'), 
  (SELECT EXERCISE_ID FROM EXERCISES WHERE EXERCISE_NAME = 'Fekvenyomás')
);

INSERT INTO WORKOUT_EXERCISES (WORKOUT_ID, EXERCISE_ID)
VALUES (
  (SELECT WORKOUT_ID FROM WORKOUTS W 
     JOIN USERS U ON W.USER_ID = U.USER_ID
     JOIN MUSCLE_GROUP M ON W.MUSCLE_GROUP_ID = M.MUSCLE_GROUP_ID
   WHERE U.USERNAME = 'user1'
     AND M.MUSCLE_GROUP_NAME = 'Mell-Bicepsz'
     AND W.WORKOUT_DATE = DATE '2024-12-01'), 
  (SELECT EXERCISE_ID FROM EXERCISES WHERE EXERCISE_NAME = 'Húzódzkodás')
);

COMMIT;




--10 workout_results betöltés
INSERT INTO WORKOUT_RESULTS (WORKOUT_EXERCISE_ID, WEIGHT_USED, REPS)
VALUES (
  (SELECT WORKOUT_EXERCISE_ID 
   FROM WORKOUT_EXERCISES WE
   JOIN WORKOUTS W ON WE.WORKOUT_ID = W.WORKOUT_ID
   JOIN USERS U ON W.USER_ID = U.USER_ID
   JOIN MUSCLE_GROUP M ON W.MUSCLE_GROUP_ID = M.MUSCLE_GROUP_ID
   JOIN EXERCISES E ON WE.EXERCISE_ID = E.EXERCISE_ID
   WHERE U.USERNAME = 'user1'
     AND M.MUSCLE_GROUP_NAME = 'Mell-Bicepsz'
     AND E.EXERCISE_NAME = 'Fekvenyomás'
     AND W.WORKOUT_DATE = DATE '2024-12-01'
  ),
  80.5,
  10
);


COMMIT;











