--Felhasználó tábla
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    CREATED_AT DATE DEFAULT SYSDATE
);

--Edzések tábla
CREATE TABLE WORKOUTS (
    WORKOUT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER REFERENCES USERS(USER_ID),
    WORKOUT_NAME VARCHAR2(100) NOT NULL,
    WORKOUT_DATE DATE NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);

--Gyakorlatok tábla
CREATE TABLE EXERCISES (
    EXERCISE_ID NUMBER PRIMARY KEY,
    EXERCISE_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(255)
);

--Edzés-Gyakorlat kapcsoló tábla
CREATE TABLE WORKOUT_EXERCISES (
    WORKOUT_EXERCISE_ID NUMBER PRIMARY KEY,
    WORKOUT_ID NUMBER REFERENCES WORKOUTS(WORKOUT_ID),
    EXERCISE_ID NUMBER REFERENCES EXERCISES(EXERCISE_ID),
    ORDER_NUMBER NUMBER, -- Gyakorlat sorrendje az edzésben
    CREATED_AT DATE DEFAULT SYSDATE
);

--Teljesített gyakorlatok tábla
CREATE TABLE WORKOUT_RESULTS (
    RESULT_ID NUMBER PRIMARY KEY,
    WORKOUT_EXERCISE_ID NUMBER REFERENCES WORKOUT_EXERCISES(WORKOUT_EXERCISE_ID),
    WEIGHT_USED NUMBER(5,2), -- Használt súly kg-ban
    REPS NUMBER, -- Ismétlések száma
    PERFORMED_AT DATE DEFAULT SYSDATE
);


/*2. Kapcsolatok és logikai összefüggések
USERS → WORKOUTS: Egy felhasználó több edzést is tervezhet. (1:N kapcsolat)
WORKOUTS → WORKOUT_EXERCISES: Egy edzés több gyakorlatból állhat. (1:N kapcsolat)
EXERCISES → WORKOUT_EXERCISES: Egy gyakorlat több edzéshez is tartozhat. (1:N kapcsolat)
WORKOUT_EXERCISES → WORKOUT_RESULTS: Egy edzés-gyakorlat pároshoz tartozik a teljesítmény adatok rögzítése. (1:N kapcsolat)*/
