

-- USERS tábla
CREATE TABLE USERS (
    USER_ID        NUMBER        NOT NULL,
    USERNAME       VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD       VARCHAR2(100) NOT NULL,
    EMAIL          VARCHAR2(100),
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    CREATED_BY     VARCHAR2(50),
    UPDATED_AT     DATE,
    UPDATED_BY     VARCHAR2(50),
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT CK_USERS_EMAIL_FORMAT CHECK (EMAIL IS NULL OR INSTR(EMAIL, '@') > 0)
);


-- MUSCLE_GROUP tábla
CREATE TABLE MUSCLE_GROUP (
    MUSCLE_GROUP_ID   NUMBER         NOT NULL,
    MUSCLE_GROUP_NAME VARCHAR2(100)  NOT NULL,
    DESCRIPTION       VARCHAR2(255),
    CREATED_AT        DATE           DEFAULT SYSDATE NOT NULL,
    CREATED_BY        VARCHAR2(50),
    UPDATED_AT        DATE,
    UPDATED_BY        VARCHAR2(50),
    CONSTRAINT PK_MUSCLE_GROUP PRIMARY KEY (MUSCLE_GROUP_ID)
);


-- WORKOUTS tábla
CREATE TABLE WORKOUTS (
    WORKOUT_ID       NUMBER      NOT NULL,
    USER_ID          NUMBER      NOT NULL,
    MUSCLE_GROUP_ID  NUMBER      NOT NULL,
    WORKOUT_DATE     DATE        NOT NULL,
    CREATED_AT       DATE        DEFAULT SYSDATE NOT NULL,
    CREATED_BY       VARCHAR2(50),
    UPDATED_AT       DATE,
    UPDATED_BY       VARCHAR2(50),
    CONSTRAINT PK_WORKOUTS PRIMARY KEY (WORKOUT_ID),
    CONSTRAINT FK_WO_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_WO_MUSCLEG FOREIGN KEY (MUSCLE_GROUP_ID)
        REFERENCES MUSCLE_GROUP(MUSCLE_GROUP_ID)
        ON DELETE CASCADE
);


-- EXERCISES tábla
CREATE TABLE EXERCISES (
    EXERCISE_ID     NUMBER         NOT NULL,
    EXERCISE_NAME   VARCHAR2(100)  NOT NULL,
    DESCRIPTION     VARCHAR2(255),
    CREATED_AT      DATE           DEFAULT SYSDATE NOT NULL,
    CREATED_BY      VARCHAR2(50),
    UPDATED_AT      DATE,
    UPDATED_BY      VARCHAR2(50),
    CONSTRAINT PK_EXERCISES PRIMARY KEY (EXERCISE_ID)
);


-- WORKOUT_EXERCISES tábla
CREATE TABLE WORKOUT_EXERCISES (
    WORKOUT_EXERCISE_ID  NUMBER      NOT NULL,
    WORKOUT_ID           NUMBER      NOT NULL,
    EXERCISE_ID          NUMBER      NOT NULL,
    CREATED_AT           DATE        DEFAULT SYSDATE NOT NULL,
    CREATED_BY           VARCHAR2(50),
    UPDATED_AT           DATE,
    UPDATED_BY           VARCHAR2(50),
    CONSTRAINT PK_WO_EX PRIMARY KEY (WORKOUT_EXERCISE_ID),
    CONSTRAINT FK_WE_WORKOUT FOREIGN KEY (WORKOUT_ID)
        REFERENCES WORKOUTS(WORKOUT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_WE_EXERCISE FOREIGN KEY (EXERCISE_ID)
        REFERENCES EXERCISES(EXERCISE_ID)
        ON DELETE CASCADE
);


-- WORKOUT_RESULTS tábla
CREATE TABLE WORKOUT_RESULTS (
    RESULT_ID            NUMBER       NOT NULL,
    WORKOUT_EXERCISE_ID  NUMBER       NOT NULL,
    WEIGHT_USED          NUMBER(5,2),  
    REPS                 NUMBER,
    PERFORMED_AT         DATE         DEFAULT SYSDATE NOT NULL,
    CREATED_AT           DATE         DEFAULT SYSDATE NOT NULL,
    CREATED_BY           VARCHAR2(50),
    UPDATED_AT           DATE,
    UPDATED_BY           VARCHAR2(50),
    CONSTRAINT PK_RESULTS PRIMARY KEY (RESULT_ID),
    CONSTRAINT FK_WR_WO_EX_ID FOREIGN KEY (WORKOUT_EXERCISE_ID)
        REFERENCES WORKOUT_EXERCISES(WORKOUT_EXERCISE_ID)
        ON DELETE CASCADE
);


-- AUDIT_LOG tábla
CREATE TABLE AUDIT_LOG (
    LOG_ID      NUMBER       NOT NULL,
    TABLE_NAME  VARCHAR2(50) NOT NULL,
    ACTION_TYPE VARCHAR2(10) NOT NULL,
    USERNAME    VARCHAR2(50) NOT NULL,
    ACTION_DATE DATE         DEFAULT SYSDATE NOT NULL,
    CREATED_AT  DATE         DEFAULT SYSDATE NOT NULL,
    CREATED_BY  VARCHAR2(50),
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LOG_ID)
);


-- MY_REPORT tábla
CREATE TABLE MY_REPORT (
    REPORT_ID        NUMBER        NOT NULL,
    USER_ID          NUMBER,
    TOTAL_WORKOUTS   NUMBER,
    TOTAL_EXERCISES  NUMBER,
    CREATED_AT       DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MY_REPORT PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_MY_REPORT_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);


-- MY_WORKOUT_REPORT tábla
CREATE TABLE MY_WORKOUT_REPORT (
    REPORT_ID           NUMBER       NOT NULL,
    USER_ID             NUMBER       NOT NULL,
    WORKOUT_ID          NUMBER       NOT NULL,
    WORKOUT_DATE        VARCHAR2(10),
    MUSCLE_GROUP_NAME   VARCHAR2(100),
    TOTAL_EXERCISES     NUMBER,
    TOTAL_REPS          NUMBER,
    TOTAL_WEIGHT        NUMBER(10,2),
    CREATED_AT          DATE         DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_MY_WORKOUT_REPORT PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_MY_WR_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);


COMMIT;
