CREATE INDEX IDX_WORKOUT_USER ON WORKOUTS(USER_ID);
CREATE INDEX IDX_WORKOUT_EXERCISE ON WORKOUT_EXERCISES(WORKOUT_ID, EXERCISE_ID);
CREATE INDEX IDX_RESULT_EXERCISE ON WORKOUT_RESULTS(WORKOUT_EXERCISE_ID);
