--listázza a felhasználók edzéseit, dátumokkal és edzésnevekkel együtt.
CREATE OR REPLACE VIEW USER_WORKOUTS_VIEW AS
SELECT 
    W.WORKOUT_ID,
    U.USERNAME,
    W.WORKOUT_NAME,
    TO_CHAR(W.WORKOUT_DATE, 'YYYY-MM-DD') AS WORKOUT_DATE
FROM WORKOUTS W
JOIN USERS U ON W.USER_ID = U.USER_ID;

--információt ad az edzésekrõl, gyakorlatokról és teljesítményrõl.
CREATE OR REPLACE VIEW WORKOUT_EXERCISE_RESULTS_VIEW AS
SELECT 
    W.WORKOUT_NAME,
    E.EXERCISE_NAME,
    R.WEIGHT_USED,
    R.REPS,
    TO_CHAR(R.PERFORMED_AT, 'YYYY-MM-DD HH24:MI:SS') AS PERFORMED_AT
FROM WORKOUTS W
JOIN WORKOUT_EXERCISES WE ON W.WORKOUT_ID = WE.WORKOUT_ID
JOIN EXERCISES E ON WE.EXERCISE_ID = E.EXERCISE_ID
JOIN WORKOUT_RESULTS R ON WE.WORKOUT_EXERCISE_ID = R.WORKOUT_EXERCISE_ID;

--összesített statisztikát jelenít meg az edzésekrõl
CREATE OR REPLACE VIEW EXERCISE_STATS_VIEW AS
SELECT 
    E.EXERCISE_NAME,
    COUNT(R.RESULT_ID) AS TOTAL_SETS,
    SUM(R.REPS) AS TOTAL_REPS,
    AVG(R.WEIGHT_USED) AS AVG_WEIGHT
FROM EXERCISES E
JOIN WORKOUT_EXERCISES WE ON E.EXERCISE_ID = WE.EXERCISE_ID
JOIN WORKOUT_RESULTS R ON WE.WORKOUT_EXERCISE_ID = R.WORKOUT_EXERCISE_ID
GROUP BY E.EXERCISE_NAME;
