--edzéshez tartozó összes ismétlés lekérdezése

CREATE OR REPLACE FUNCTION GET_TOTAL_REPS_BY_WORKOUT(W_ID NUMBER) 
RETURN NUMBER IS
    TOTAL_REPS NUMBER := 0;
BEGIN
    SELECT NVL(SUM(R.REPS), 0)
    INTO TOTAL_REPS
    FROM WORKOUT_RESULTS R
    JOIN WORKOUT_EXERCISES WE ON R.WORKOUT_EXERCISE_ID = WE.WORKOUT_EXERCISE_ID
    WHERE WE.WORKOUT_ID = W_ID;
    
    RETURN TOTAL_REPS;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20025, 'HIBA: Nem sikerült lekérdezni az összes ismétlést.');
END;
/



--kiszámolja, hogy az adott user összesen hány kilógramm súlyt emelt meg.
CREATE OR REPLACE FUNCTION TOTAL_WEIGHT_BY_USER_WORKOUT (
    P_USER_ID IN NUMBER,
    P_WORKOUT_ID IN NUMBER
) RETURN NUMBER IS
    TOTAL_WEIGHT NUMBER := 0;
BEGIN
    SELECT NVL(SUM(R.REPS * R.WEIGHT_USED), 0)
    INTO TOTAL_WEIGHT
    FROM WORKOUT_RESULTS R
    JOIN WORKOUT_EXERCISES WE ON R.WORKOUT_EXERCISE_ID = WE.WORKOUT_EXERCISE_ID
    JOIN WORKOUTS W ON WE.WORKOUT_ID = W.WORKOUT_ID
    WHERE W.USER_ID = P_USER_ID
      AND W.WORKOUT_ID = P_WORKOUT_ID;

    RETURN TOTAL_WEIGHT;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20027, 'HIBA: Nem sikerült lekérdezni az összes megemelt súlyt.');
END;
/





