-- USER TÁBLA
SELECT * FROM USERS;
--MUSCLE_GROUP TÁBLA
SELECT * FROM MUSCLE_GROUP;
--WORKOUTS TÁBLA
SELECT * FROM WORKOUTS;
--EXERCISE TÁBLA
SELECT * FROM EXERCISES;
--WORKOUT-EXERCISE TÁBLA
SELECT * FROM WORKOUT_EXERCISES;
--WORKOUT_RESULTS TÁBLA
SELECT * FROM WORKOUT_RESULTS;
--AUDIT LOG TÁBLA
SELECT * FROM AUDIT_LOG;



--VIEW TESZT

--1. USER_WORKOUTS_VIEW
SELECT * FROM USER_WORKOUTS_VIEW;
--2.
SELECT * FROM WORKOUT_EXERCISE_RESULTS_VIEW;
--3.
SELECT * FROM EXERCISE_STATS_VIEW;



--FUNCTION TESZT
--1.
SELECT GET_TOTAL_REPS_BY_WORKOUT(1) AS TOTAL_REPS FROM DUAL;
--2.
SELECT TOTAL_WEIGHT_BY_USER_WORKOUT(1, 1) AS TOTAL_WEIGHT FROM DUAL;




--PROC 
--1.
DECLARE
    V_TOTAL_WORKOUTS NUMBER;
    V_TOTAL_EXERCISES NUMBER;
BEGIN
    WORKOUT_AND_EXERCISE_COUNT(4, V_TOTAL_WORKOUTS, V_TOTAL_EXERCISES);
    DBMS_OUTPUT.PUT_LINE('Osszes edzes: ' || V_TOTAL_WORKOUTS);
    DBMS_OUTPUT.PUT_LINE('Osszes gyakorlat: ' || V_TOTAL_EXERCISES);
END;
/
--2.
BEGIN
    GENERATE_USER_WORKOUT_REPORT(5);
END;
/









--TRIGGER TESZTELÉSEK
--1. az email nem tartalmaz '@' jelet ezért --> hiba
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) 
VALUES ('testuser', 'invalid_email', 'pass123');

--2.
INSERT INTO WORKOUTS (USER_ID, MUSCLE_GROUP_ID, WORKOUT_DATE)
VALUES (1, 2, SYSDATE);

--3. kapcsolodó eredmények miatt az edzés nem törölhetõ --> hiba
DELETE FROM WORKOUTS WHERE WORKOUT_ID = 1;

--4. meglévõ edzés idejének (vagy bármi más) átállítása --> AUDIT_LOG-ba új rekord kerül.
UPDATE WORKOUTS SET WORKOUT_DATE = SYSDATE WHERE WORKOUT_ID = 1;
SELECT * FROM AUDIT_LOG;















