GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON WORKOUTS TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXERCISES TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON WORKOUT_EXERCISES TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON WORKOUT_RESULTS TO app_user;
